{"name": "test_post_create_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert None\n +  where None = validate_positive_requests({'status': 'success'}, 'GetUserByNickname')\n +    where validate_positive_requests = <autotests.services.users.models.user_validation.ResponseValidator object at 0x000001ED6F0FCE10>.validate_positive_requests", "trace": "self = <autotests.test_users.TestUsers object at 0x000001ED6EFB3390>, create_and_delete_user = {'status': 'success'}\nresponse_validator = <autotests.services.users.models.user_validation.ResponseValidator object at 0x000001ED6F0FCE10>\n\n    @allure.story('Create user positive')\n    @pytest.mark.api_positive\n    def test_post_create_user(self, create_and_delete_user, response_validator):\n    \n>       assert response_validator.validate_positive_requests(create_and_delete_user,'GetUserByNickname')\nE       AssertionError: assert None\nE        +  where None = validate_positive_requests({'status': 'success'}, 'GetUserByNickname')\nE        +    where validate_positive_requests = <autotests.services.users.models.user_validation.ResponseValidator object at 0x000001ED6F0FCE10>.validate_positive_requests\n\nautotests\\test_users.py:21: AssertionError"}, "start": 1753204053945, "stop": 1753204053949, "uuid": "8a5e93a4-9d56-4f2f-9ec7-d3b089893f15", "historyId": "d17486994c057395c4954952002e6ad1", "testCaseId": "d17486994c057395c4954952002e6ad1", "fullName": "test_users.TestUsers#test_post_create_user", "labels": [{"name": "story", "value": "Create user positive"}, {"name": "feature", "value": "User API"}, {"name": "tag", "value": "api_positive"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-KHTU12F"}, {"name": "thread", "value": "12404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_users"}]}