{"name": "test_post_create_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'FakeUser' object has no attribute 'generate_user'", "trace": "@pytest.fixture()\n    def random_user():\n        generator = FakeUser()\n>       return generator.generate_user()\nE       AttributeError: 'FakeUser' object has no attribute 'generate_user'\n\nautotests\\conftest.py:17: AttributeError"}, "start": 1752934901433, "stop": 1752934901433, "uuid": "24c6d704-d77c-4861-8e54-ea7a50dc0a68", "historyId": "d17486994c057395c4954952002e6ad1", "testCaseId": "d17486994c057395c4954952002e6ad1", "fullName": "test_users.TestUsers#test_post_create_user", "labels": [{"name": "feature", "value": "User API"}, {"name": "story", "value": "Create user positive"}, {"name": "tag", "value": "api_positive"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-KHTU12F"}, {"name": "thread", "value": "5788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_users"}]}