{"uuid": "f38b6d2f-bd99-4e18-9e1f-86631ba14132", "children": ["24c6d704-d77c-4861-8e54-ea7a50dc0a68"], "befores": [{"name": "random_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'FakeUser' object has no attribute 'generate_user'\n", "trace": "  File \"C:\\Users\\mark\\PycharmProjects\\curve\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mark\\PycharmProjects\\curve\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\mark\\PycharmProjects\\curve\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\mark\\PycharmProjects\\curve\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\mark\\PycharmProjects\\curve\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\mark\\PycharmProjects\\curve\\autotests\\conftest.py\", line 17, in random_user\n    return generator.generate_user()\n           ^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1752934901435, "stop": 1752934901436}], "start": 1752934901435, "stop": 1752934901604}